query getCharacter($id: ID!) {
  character(id: $id) {
    id
    created
    gender
    name
    image
    species
    origin {
      id
      dimension
      name
      type
    }
    status
    type
  }
}
